spring:
  application:
    name: ${APP_NAME:unnamed}
  datasource:
    url: jdbc:mysql://localhost:3306/leanjdbc2?useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456
    dirver-class-name: com.mysql.jdbc.JDBCDriver
    # HikariCP配置:
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1

server:
  port: ${APP_PORT:8080}

pebble:
  suffix:
  cache: false

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, env, metrics

---

spring:
  profiles: test

server:
  port: 8000

---

spring:
  profiles: production

server:
  port: 80

pebble:
  cache: true

management:
  endpoints:
    web:
      exposure:
        include: info, health
